// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Stockimulate.Views.AdministratorViews {
	
	
	public partial class AdminPanel {
		
		protected System.Web.UI.WebControls.Content AdminContent;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl IndexButtonGroup;
		
		protected System.Web.UI.WebControls.Button PlayPracticeButton;
		
		protected System.Web.UI.WebControls.Button PlayCompetitionButton;
		
		protected System.Web.UI.WebControls.Button ContinueButton;
		
		protected System.Web.UI.WebControls.Button ResetTradesButton;
		
		protected System.Web.UI.WebControls.Button FixTradesButton;
		
		protected System.Web.UI.HtmlControls.HtmlInputCheckBox VerifyInput;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ErrorDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl WarningDiv;
		
		protected System.Web.UI.WebControls.DropDownList SecurityDropDownList;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl PriceInput;
		
		protected System.Web.UI.WebControls.Button UpdatePrice;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl ReportsEnabledSpan;
		
		protected System.Web.UI.WebControls.Button ToggleReportsEnabled;
	}
}
